scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["127.0.0.1:9090"]
  #以下是traefk的metrics的监控地址
  - job_name: "traefik"
    static_configs:
      - targets: ["miao-traefik:8080"]